### ISSUE TITLE
GPU falling behind during live basecalling, not fully utilized. 

### ISSUE THREAD

**Issue by faulk-lab** [nanoporetech/dorado#424] opened 2023-10-18 20:19 UTC
I'm running a P2 Solo connected to a machine with dual 4090s. During the minknow run, my base calling falls far behind and the GPUs are not fully utilized. However when I basecall post-hoc with dorado, both GPUs max out and finish in far less time than the entire sequencing run took. How can I get minknow's version of dorado to use both GPUs to full capacity and keep up so that I don't have to re-basecall after every run.

Example: I just ran a flow cell for 24 hours, in minknow selecting super accuracy with 5mC_5hmC modified calls. It sequenced an estimated 40 Gb, but has only base called 11.8 Gb in that time.

On an identical computer that is not base calling, I basecalled 40 Gb worth of R10.4.1 data in less than 12 hours. 

Minknow's call to dorado from the logs is this:
`2023-10-17 16:04:41.602776 [guppy/info] CONNECT client request. ["dna_r10.4.1_e8.2_400bps_5khz_modbases_5hmc_5mc_cg_sup_prom:>timeout_interval=15000>client_name=A_f03218b6-3874-442e-883d-ddc11ee78540>barcode_kits=>detect_barcodes=0>align_ref=/home/minknow/Desktop/genomes/mouse/mm39.mmi>move_and_trace_enabled=1>post_out=0>do_read_splitting=1"]`

My post-hoc call to dorado is this:
`~/Desktop/dorado-0.4.1-linux-x64/bin/dorado basecaller ~/Desktop/dorado-0.4.1-linux-x64/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 ../raw-data-mouse/ --modified-bases 5mCG_5hmCG -r --reference ~/Desktop/genomes/mouse/mm39.fa > mouse.unsort.bam`

**Comment by faulk-lab** [comment] 2023-10-18 20:23
PS. The GPU utilization during the run is only 20-50% on average. Screenshot below.
<img width="882" alt="Screen Shot 2023-10-18 at 3 22 50 PM" src="https://github.com/nanoporetech/dorado/assets/123518154/e6bcf65f-332f-4285-a4dd-bc5ece1f722a">

**Comment by vellamike** [comment] 2023-10-20 13:36
Hi @faulk-lab  - could you confirm which version of MinKnow you are using?

**Comment by faulk-lab** [comment] 2023-10-20 14:32
I'm using 23.07.12, the latest version available for linux with GPU support.

**Comment by faulk-lab** [comment] 2023-10-22 04:26
It's heat. 

It took me a LOT of detective work to figure this out but it came down to thermal throttling by the CPU. I am using an AMD 7950x based system with an AIO cooler and dual air-cooled 4090s. When I basecall post-hoc, the GPUs are pegged out at 100% usage, and their integrated coolers do the job, they never go above 65-70 degrees C.

My CPU speed starts off fast, 2-4 Ghz range, and this model CPU is hard to gauge the temperature because it will boost until it hits 95 degrees, so watching its temperature is kind of pointless. However, watching the FREQUENCY is key. I notice that after an hour or two, the GPUs are no longer running at 100%, they are choppy as in the image I pasted above. Turns out, my CPU has downclocked itself to 400-500 Mhz due to too much heat in the AIO loop, and it's not effectively cooling the CPU anymore. It's running so slowly that it cannot transfer the data from the SSDs to the GPUs fast enough to fully utilize them anymore.

I'm pretty sure this is what is happening during my runs also. That's why the base calling keeps up for a few hours, then starts to lag. It's also a difficult problem to diagnose because it doesn't appear until the whole machine gets pretty warm which can take a long time.

I'm looking into optimizing the cooling on my computer now. Hopefully that will solve it.

**Comment by Psy-Fer** [comment] 2023-10-22 05:02
Hey,

Hit me up if you want some help with the machine.

I would suggest a heat pipe cooler, like the ones from noctua. They keep our threadripper pumping with our 3080/3070 build.

Another one is to check the orientation of the AIO to make sure you are getting proper efficiency out of the pump and not having air bubble issues.

**Comment by vellamike** [comment] 2023-10-22 21:24
Thanks @faulk-lab  - if the CPU has been down-clocked due to thermal throttling then this would indeed lead to the GPUs being starved.

Could you try and run without alignment and let me know what happens? This would put less stress on the CPU.

**Comment by faulk-lab** [comment] 2023-10-22 22:19
Progress update: I replaced the AIO cooler which had failed. Now my CPU is running at sustained > 5 ghz like it's supposed to. That was definitely a major problem and was causing sporadic shutdowns. I restarted base calling and it was using both GPUs at 100% and base calling rapidly. After a few hours a new problem appeared.

New problem: Basecalling appeared to slow down after few hours, however the GPUs both appeared to be using nearly 100% GPU processor, though some choppiness had appeared. The CPU temp and speed were both fine now with the new AIO. The only way I detected a problem was that the PCIE bandwidth going to each GPU dropped from ~80% down to ~3%. Oddly they were still using > 400 watts each, and they were base calling, just *very slowly*. Clearly the data transfer rate dropped off a cliff. Watching NVIDIA settings is the only way I knew a problem was happening, outside of very slow base calling. PS. I would be great to see "live" base calling speed. PPS. Upon "resume-from", the progress bar and time estimation seem to freeze.

I noticed the upper GPU was using less PCIE bandwidth (~60%) even when base calling at high speed. I assume this was due to it being hotter? It was running ~70 degrees vs. 55 degrees for the lower one.

I have restarted base calling again using only 1 GPU, the lower one. It's calling about 33 Mb per minute. I don't know if that is good or bad, but it's half as fast as both GPUs when they start cold, and much faster than when they have run for a couple hours.

**Comment by faulk-lab** [comment] 2023-10-22 22:37
Per your suggestion, I just launched a dorado instance on the upper GPU without alignment, since it was idle. Timing it with a stopwatch, I am seeing these rates per 100 Mb of basecalling:
34 Mb/minute - no alignment
36 Mb/minute - with alignment

This is with both instances freshly started (resumed from the same bam anyway). I'll let both run each on a separate GPU and wait to see if they lose PCIE bandwidth and become choppy. Again, when that happens, the CPU temp and speed are fine. The GPU temps are fine and they keep using the same amount of electricity, but basecalling speed plummets with along PCIE bandwidth. Weird problem. Relaunching with resume gets the speed back up, even if it's done immediately, so temperatures doesn't seem to be the cause. I am open to ideas.

**Comment by faulk-lab** [comment] 2023-10-23 03:39
Update: The problem appears even without alignment enabled. Runs fine for ~1 hr, then goes choppy, slow base calling, and low PCIE bandwidth utilization. Same as with alignment turned on.

**Comment by faulk-lab** [comment] 2023-10-23 05:17
Tried lowering the batch size to 640, down from 960 as set by auto batch size. The problem persists.

**Comment by vellamike** [comment] 2023-10-25 07:29
Hi @faulk-lab 

> Basecalling appeared to slow down after few hours, however the GPUs both appeared to be using nearly 100% GPU processor, though some choppiness had appeared. The CPU temp and speed were both fine now with the new AIO. The only way I detected a problem was that the PCIE bandwidth going to each GPU dropped from ~80% down to ~3%. Oddly they were still using > 400 watts each, and they were base calling, just very slowly. 

Just to be clear - is this using Dorado standalone or with MinKnow?  It's not completely clear to me yet whether the issue you are seeing is MinKNOW-related or not.

When you say that the GPUs are using  > 400 watts each but basecalling very slowly, something isn't quite adding up there - how can you tell that they are basecalling slowly?

**Comment by faulk-lab** [comment] 2023-10-25 14:05
Hi vellamike, thanks for getting back to me. I'm using dorado standalone v4.1.0 for base calling of R10.4.1 flow cell data from a P2 Solo run with a 114 ligation kit. I am checking base calling speed 2 ways, 1) simply by watching the size of the output .bam file. It starts off by growing at a rate of 100 mb every 2 minutes. That rate is very steady. Then *suddenly* after an hour or so, it slows down to grow at a rate of 100 mb every 30 minutes roughly. 2) I am watching the estimated time for the run. It starts by showing ~20 hours, when it's base calling quickly in the beginning, then it jumps to 3 days when it slows down.

I am watching the energy use by nvtop. At first it's a solid line with 100% usage, base calling quickly. When it slows down, the usage pattern becomes choppy, along with power usage. So yes, it does start to use less power, but not zero, still bounces between 0% and 100%. It's almost like there's a transfer bottleneck or something is growing and causing problems with a queue. Ram usage is steady and fairly low.

**Comment by faulk-lab** [comment] 2023-10-29 02:14
Ok. I finally definitively figured it out. It turns out that Minknow is producing some fast5 format files in a directory called *"fast5_skip"* even when all output *should* be in pod5 format. In my P2 solo run directories (23.07.12) I have "pod5_pass", "pod5_fail", and "pod5_skip" along with *"fast5_skip"*. Obviously fast5_skip should not exist. For example, my recent run had ~70 Gb of data in fast5 format in there. While dorado can technically basecall fast5, it does so *extremely* slowly in many cases. 

That's what I was seeing in my posthoc base calling. I fed dorado the entire run directory with "-r" recursive turned on and didn't check to see if there were any errant fast5 files in there. Those were gumming up the works. When I ran dorado against only the pod5 directories, there was no slow-down and everything worked fine. I believe these fast5 files are creating the stall during the run *and* when I post-hoc base call. It was going fast initially because it was calling the pod5s. When it hit the fast5s, it hit a wall and slowed dramatically. As long as I exclude the fast5_skip directory and *only* call pod5s, everything goes smoothly.

This can be fixed by updating Minknow so that it does not create *any* fast5s  when selecting pod5 as the default option.

**Comment by tijyojwad** [comment] 2023-10-29 22:49
Thanks for the deep dive and for sharing the root cause! This will be very helpful for future users.

As you mentioned, pod5 is the data format dorado is optimized for. fast5 is supported for legacy reasons but we don't focus on it for performance. Let us know if you still see fast5s after updating the Minknow version. I'll close it as resolved for now with no action required from dorado.

**Closed by tijyojwad** 2023-10-29 22:49 UTC

**Comment by tijyojwad** [comment] 2023-10-29 22:51
Actually, perhaps we can report a warning when we encounter both fast5 and pod5 files during data loading. That can help highlight the issue for other users too, and save them a lot of debugging time.

**Comment by faulk-lab** [comment] 2023-10-29 23:07
A warning would be helpful as it would have saved me a ton of troubleshooting time, and I guarantee this is happening to others because Minknow appears to be doing this by default.

Also, I don't know how to inform the Minknow team. This problem prevents live basecalling from working properly.

**Comment by tijyojwad** [comment] 2023-11-02 15:32
Hi @faulk-lab - this bug has been fixed in MinKnow and will be available as part of the next release.

**Comment by gallardo-seq** [comment] 2023-11-03 19:34
Hi everyone, can anybody (from ONT or otherwise), confirm if the fast5_skip and pod5_skip directories in this context hold duplicate reads? Would really appreciate any info.

**Comment by ckdabk** [comment] 2024-12-12 20:18
Hello @faulk-lab, my own lab is considering building a PC to perform live basecalling with our MinION Mk1B, and I'd like to ask you about your experience. Is a high end CPU as important as a GPU for basecalling?
