### ISSUE TITLE
Dorado memory management

### ISSUE THREAD

**Issue by HITzhongyu** [nanoporetech/dorado#283] opened 2023-07-05 07:49 UTC
Hi 
I encountered an out-of-memory error while using Dorado. My input is a 325G pod5 and I'm running the basecaller on Dorado. I submitted the job on a Linux server with 470G of memory and 30 threads. Despite this configuration, Dorado still reported a memory error.

` sbatch --partition=local --mem=470g --mincpus=30 --output=$line.log /home/user/ydliu/hitbic/gpu.sh  $line`

gpu.sh as shown below
```
#!/bin/bash
. ~/.bashrc
conda activate remora
line="$1"
/home/user/ydliu/software/dorado-0.3.1-linux-x64/bin/dorado basecaller /home/user/ydliu/software/dorado-0.3.1-linux-x64/model/dna_r9.4.1_e8_hac@v3.3/  "$line"/pod5/ --emit-moves -x cuda:0,1,2,3,4,5,6,7 >  "$line"/calls.bam 
```

the  error log  as shown below
```
[2023-07-05 14:45:52.855] [info] > Creating basecall pipeline
/var/spool/slurm/d/job02512/slurm_script: line 10: 40134 Killed                  /home/user/ydliu/software/dorado-0.3.1-linux-x64/bin/dorado basecaller /home/user/ydliu/software/dorado-0.3.1-linux-x64/model/dna_r9.4.1_e8_hac@v3.3/ "$line"/pod5/ --emit-moves -x cuda:0,1,2,3,4,5,6,7 > "$line"/calls.bam
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=2512.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
I first confirmed that there was sufficient GPU memory available
![image](https://github.com/nanoporetech/dorado/assets/104176070/32899d61-5957-468f-9f70-5c576b765b5e)

and  I tried to check the memory usage of the submitted task, as shown below.
![image](https://github.com/nanoporetech/dorado/assets/104176070/50936159-bb97-4d18-adc9-ef4a6e689301)

**Comment by tijyojwad** [comment] 2023-07-05 12:36
Hi @HITzhongyu - thanks for reporting this. This is a bit unusual, since we haven't seen simplex basecalling requiring so much memory. We recently pushed some code to further limit the memory usage, so that may have already fixed the problem (it was committed after the 0.3.1 release). We'll attempt to reproduce this issue internally as well.

**Comment by HITzhongyu** [comment] 2023-07-06 00:31
Hi @tijyojwad   
My dorado version is  0.3.1, this should be the latest version.
![image](https://github.com/nanoporetech/dorado/assets/104176070/390e13e7-0d95-410b-a2a9-8a125c249b85)

**Comment by tijyojwad** [comment] 2023-07-06 01:51
Right, the changes are in but they went in after the 0.3.1 release was cut, so we don't have a binary with those changes yet.

I'm attempting to reproduce this internally to see if it still persist.

**Comment by HITzhongyu** [comment] 2023-07-06 06:55
@tijyojwad  
I want to know how long it is expected to take to fix this, or if the segmentation fault in previous versions affects the results. If it does not affect the results, can we use the previous version?

**Comment by tijyojwad** [comment] 2023-07-07 02:28
Hi @HITzhongyu - we are hoping to release the next patch within a few days.

You can use the past version (like 0.3.0) if that works for you. If the segmentation fault you're seeing occurs at the end of the run, then typically all records are written, but the file may not be closed properly. So the BAM may be missing EOF markers. If you fix that, you should be okay.

Also I wasn't able to reproduce OOM on our latest internal branch. I ran with `--emit-moves` on a 500GB pod5 dataset and saw memory around 20GB. But it could be dependent on your dataset too. So would be good for you to evaluate the next patch once its released.

**Comment by HITzhongyu** [comment] 2023-07-07 02:31
@tijyojwad 
I appreciate your response and look forward to the release of the new version as soon as possible！

**Comment by tijyojwad** [comment] 2023-07-31 21:48
Hi @HITzhongyu - apologies for the late notification. We released a newer version with some host memory improvements a couple of weeks ago (release [notes](https://github.com/nanoporetech/dorado/releases/tag/v0.3.2) and new [binaries](https://github.com/nanoporetech/dorado#installation)). Can you give it a try and let me know if you still see issues?

Unfortunately I wasn't able to reproduce host OOM with the move table even on large datasets.

**Comment by jonathonthill** [comment] 2023-08-05 17:06
I am seeing the same issue, and like the previous user I am using slurm to manage jobs on a large computing core. Could there be a specific memory management problem when working in slurm?

**Comment by jonathonthill** [comment] 2023-08-05 17:07
<img width="1289" alt="image" src="https://github.com/nanoporetech/dorado/assets/6608133/c912d863-78fb-4f33-b4b7-ac044fc8003c">

**Comment by tijyojwad** [comment] 2023-08-07 14:13
> allotted 96 cores and 128 GB per core

Do I understand correctly that your job failed with `96*128=12288 GB (~12 TB)` of memory??

In case the above is a type, running basecalling + mod basecalling on CPU and running alignment can both increase memory utilization (though I don't believe it'll need terabytes). I can run some more tests to see what the memory footprint is. How large is your dataset?

**Comment by jonathonthill** [comment] 2023-08-07 14:16
> > allotted 96 cores and 128 GB per core
> 
> Do I understand correctly that your job failed with `96*128=12288 GB (~12 TB)` of memory??
> 
> In case the above is a type, running basecalling + mod basecalling on CPU and running alignment can both increase memory utilization (though I don't believe it'll need terabytes). I can run some more tests to see what the memory footprint is. How large is your dataset?

Not a typo. I am working in the BYU Research Computing Core. I started much smaller, but I kept upping it when it said out of memory. I gave up at 128GB.

**Comment by jonathonthill** [comment] 2023-08-07 14:18
Of note. I changed it to use the core's A100 gpu, and it is working fine. I have also run it without slurm, and it is fine. It appears to be a specific issue with cpu mode on slurm.

**Comment by tijyojwad** [comment] 2023-08-09 02:54
> It appears to be a specific issue with cpu mode on slurm.

Ah that is an interesting find - thanks for letting us know! I still find it quite surprising that 12TB of memory is not enough for cpu basecalling. But given cpu basecalling is orders of magnitude slower than using an A100, it's likely not a common production setup anyway. Either way, we will check whether there are any leaks when calling on CPU.

**Closed by tijyojwad** 2023-08-09 02:54 UTC
