### ISSUE TITLE
Segmentation fault when both fast5 and pod5 are present

### ISSUE THREAD

**Issue by olawa** [nanoporetech/dorado#378] opened 2023-09-19 08:14 UTC
I understand it does not make sense to keep both fast5 and pod5 but I think it would be helpful if dorado could handle this situation. Currently MinKNOW writes both fast5_skip and pod5_skip (not sure if it is the same reads yet) which causes dorado to segfault. Removing/converting fast5_skip solves this.

**Comment by vellamike** [comment] 2023-09-20 13:03
Hi @olawa , thanks for raising this. MinKNOW writes both fast5_skip and pod5_skip is a bug which will be fixed in the next release. Apologies for this. 

Regardless, Dorado should not segfault in this scenario. What command are you running?

**Comment by gallardo-seq** [comment] 2023-11-03 19:36
Hi everyone, we're having a similar issue here. Was wondering if anybody (from ONT or otherwise), can confirm if the fast5_skip and pod5_skip directories in this context are duplicate of each other? Would really appreciate any info on this.

**Comment by MarkBicknellONT** [comment] 2023-11-07 09:21
Hi @gallardo-seq - yes the fast5_skip and pod5_skip folders will contain the same set of reads.

**Comment by HalfPhoton** [comment] 2024-02-06 14:45
Dorado will now only basecall pod5 files (ignoring fast5s) if any pod5 files are found. 
This should resolve this issue - please re-open this issue if the issue persists.
Kind regards,
Rich

**Closed by HalfPhoton** 2024-02-06 14:45 UTC
Labels: bug
