### ISSUE TITLE
Basecalling model for Direct RNAseq SQK-RNA002

### ISSUE THREAD

**Issue by tir-hbdx** [nanoporetech/dorado#200] opened 2023-05-25 11:44 UTC
I am trying to use Dorado for basecalling of a Direct RNAseq dataset prepared with the SQK-RNA002 kit. Using the only available RNA model for Dorado (rna003_120bps_sup@v3) I get the error: [error] Sample rate for model (4000) and data (3012) don't match.

Is there an RNA model for Dorado compatible with this dataset?

**Comment by vetmohit89** [comment] 2023-05-26 15:58
Hello, I also got the same error 
Resetting modules to system default
[2023-05-26 10:53:13.082] [info] > Creating basecall pipeline
[2023-05-26 10:54:57.730] [error] Sample rate for model (4000) and data (3012) don't match.

**Comment by itslittman** [comment] 2023-05-26 20:54
@tir-hbdx I've used this model to basecall RNA002 data and had no error messages like that, but I'm not sure the results are reliable since it says 120bps and RNA002 translocation speed is 70bps. That being said, the resulting tracks look good in IGV. I heard there was an RNA003 kit in the works that was scrapped in favor of the upcoming RNA004 kit; maybe this SUP model was intended for RNA003 but can be used with RNA002 data and so was still released here? There's definitely no dorado version of the RNA002 HAC model I use during live basecalling, at least that I can see.

I actually came here to ask if this model produces reliable results with RNA002 and saw this thread/figured I'd jump in. If my question is too tangential I can open a new thread.

Noah

**Comment by tijyojwad** [comment] 2023-05-31 13:23
Hi @tir-hbdx @vetmohit89 - you're seeing the error because the RNA003 released models is not technically compatible with the RNA002 dataset. We will be released the correct models in a subsequent release. I'll keep the issue open so I can get back to you when that's ready.

@itslittman - you were probably running a dorado pre-`0.3.0` release, right? that _might_ be okay... but the recommendation is to update to latest dorado and use the appropriate models once we release them :)

**Comment by ChaseWLW** [comment] 2023-06-27 09:30
Hey @tijyojwad, I tried to run the just released rna002_70bps_hac@v3 model on some RNA002 datasets and got a similar error message:
[error] Sample rate for model (3000) and data (3012) don't match.

Any idea how to fix this?

**Comment by stegiopast** [comment] 2023-07-17 16:50
Hi @tijyojwad I am interested in the progress of the bugfix? Is there any release planned soon ?

**Comment by iiSeymour** [comment] 2023-07-17 16:59
@stegiopast this fix made it into the [v0.3.2](https://github.com/nanoporetech/dorado/releases/tag/v0.3.2) release from last week.

**Closed by iiSeymour** 2023-07-17 16:59 UTC
Labels: bug
