### ISSUE TITLE
Trim intervall termination

### ISSUE THREAD

**Issue by SynBioExplorer** [nanoporetech/dorado#1052] opened 2024-09-30 07:04 UTC
Hi, 

I am running dorado 080 on macos M1 Pro.
I am running the following command:
./dorado basecaller hac input_dir/pod5/  --emit-fastq --kit-name SQK-RBK114-24 --output-dir /output_dir/

This results in a termination:
[2024-09-30 16:49:35.433] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2024-09-30 16:49:35.671] [info] Assuming cert location is /etc/ssl/cert.pem
[2024-09-30 16:49:35.674] [info]  - downloading dna_r10.4.1_e8.2_400bps_hac@v5.0.0 with foundation
[2024-09-30 16:49:50.220] [info] Normalised: chunksize 10000 -> 9996
[2024-09-30 16:49:50.220] [info] Normalised: overlap 500 -> 498
[2024-09-30 16:49:50.220] [info] > Creating basecall pipeline
[2024-09-30 16:50:03.757] [info]  - set batch size to 672
libc++abi: terminating due to uncaught exception of type std::invalid_argument: Trim interval 102-99 is invalid for sequence TTTATTCGTTGGTTGTGAATTTGGTGGCACCCAACGAGTCTCTTGGGACCCATAGAGTTTTCAAATTATCGTGAAACGCTTTCGCGTTTTTAACTAATCTGAAGCGGCGCACAAAAACGCGAAAGCATTCACGATAAATGCGAAAACTCTATGGTCCCGAGACTG
zsh: abort 

When I run the same command including the "--no-trim" argument, it all works. No biggie just thought I ll let you know.

Cheers

**Comment by malton-ont** [comment] 2024-09-30 07:59
HI @SynBioExplorer,

This looks like a duplicate of https://github.com/nanoporetech/dorado/issues/1020. I'll close this one and you can follow updates there.

**Closed by malton-ont** 2024-09-30 07:59 UTC
