### ISSUE TITLE
Assertion failed: (ptr != nullptr), function mtl_for_tensor, file metal_utils.cpp, line 138.

### ISSUE THREAD

**Issue by thomasvangurp** [nanoporetech/dorado#14] opened 2022-05-29 09:39 UTC
When using either `dna_r9.4.1_e8.1_hac@v3.3` or `dna_r9.4.1_e8_hac@v3.3` i get
```
(base) mbp-van-thomas:bin thomasg$ ./dorado basecaller dna_r9.4.1_e8.1_hac@v3.3 fast5_pass
> Creating basecall pipeline
@HD	VN:1.5	SO:unknown
@PG	ID:basecaller	PN:dorado	VN:0.0.1a0	CL:dorado basecaller dna_r9.4.1_e8.1_hac@v3.3 fast5_pass
Assertion failed: (ptr != nullptr), function mtl_for_tensor, file metal_utils.cpp, line 138.
Abort trap: 6
```

**Comment by thomasvangurp** [comment] 2022-05-29 09:42
the 'fast' models `dna_r9.4.1_e8_fast@v3.4` and `dna_r9.4.1_e8.1_fast@v3.4` do yield results!

**Comment by iiSeymour** [comment] 2022-05-29 10:12
Hey @thomasvangurp 

See https://github.com/nanoporetech/dorado/issues/7#issuecomment-1136361936... for `fast` models I'd recommend `-b 1536 -r 2` and for `hac` `-b 384 -r 2`.

**Comment by iiSeymour** [comment] 2022-06-02 20:05
close as a duplicate of https://github.com/nanoporetech/dorado/issues/7

**Closed by iiSeymour** 2022-06-02 20:05 UTC
Labels: bug
