### ISSUE TITLE
Dorado only process 46% of the raw pod5 files

### ISSUE THREAD

**Issue by AyshaSezmis** [nanoporetech/dorado#220] opened 2023-06-01 19:38 UTC
Hi team,

My dorado was running the last 7 days and the process bar indicated still 8 days left to finish the base calling, but suddnely it stopped base calling. See below:
[2023-05-25 15:32:39.443] [info] > No duplex pairs file provided, pairing will be performed automatically
[2023-05-25 15:32:40.024] [info] > Starting Stereo Duplex pipeline
[2023-05-25 15:32:40.029] [info] > Reading read channel info
[2023-05-25 15:32:40.708] [info] > Processed read channel info
[█████████████▉                ] 46% [07d:09h:53m:49s<08d:13h:37m:32s] [2023-06-02 01:31:30.263] [info] > Reads skipped (qscore < 10): 565477
[2023-06-02 01:31:31.636] [info] > Reads basecalled: 4943011h:41m:04s] 
[2023-06-02 01:31:31.637] [info] > Basecalled @ Bases/s: 3.675373e+02

Why did this happen? And is there a way to restart dorado so it can continue from where it left, instead of starting from beginning?

My dorado call was as below:
#!/bin/bash

POD5="/Users/asez0001/Desktop/Dorado/POD5"
output_dir="/Users/asez0001/Desktop/Dorado"

/Users/asez0001/dorado-0.3.0-osx-arm64/bin/dorado duplex /Users/asez0001/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 \
${POD5} --min-qscore 10 > ${output_dir}/recovered_duplex.bam

Many thanks for your help,
Best wishes,
Aysha

**Comment by AyshaSezmis** [comment] 2023-06-01 20:35
Hi again,

I have just realised when i add the reads called to the reads skipped, it adds up to 100%. So this makes sense now. Dorado actually processed all of the pod5 files. 

We can close this comment,
Best wishes,
Aysha

**Comment by tijyojwad** [comment] 2023-06-01 21:05
Hi @AyshaSezmis - yes this is a bug we're working on fixing. As you said your output is fine. But our progress bar logging doesn't take into account filtered reads so the projected time is incorrect. Closing this as a duplicate of https://github.com/nanoporetech/dorado/issues/184

**Closed by tijyojwad** 2023-06-01 21:05 UTC
