### ISSUE TITLE
modified bases option significantly lowers the number of aligned reads in output bam

### ISSUE THREAD

**Issue by rainwala** [nanoporetech/dorado#302] opened 2023-07-18 08:09 UTC
Hello,

I'm running dorado version 0.3.1 (and previously 0.3.0) on a promethion R10 WGS run. When I run dorado basecaller followed by dorado aligner, using the dna_r10.4.1_e8.2_400bps_hac_v4.1.0 model, I get a bam file that is 74GB in size. When I do the same with the modified-bases option, I get a bam file that is 1.9GB in size. Using the samtools veiw command to select reads from a promoter region I am interested in gives me 75 reads from the unmodifed bam file, and only 1 read from the modified bam file.

Using the modified bases option seems to lose a lot of reads after alignment compared with the unmodified bases option., What could be causing this behaviour?

Thank you.

**Comment by iiSeymour** [comment] 2023-07-18 09:56
Hello @rainwala can you try with v0.3.2?

**Comment by rainwala** [comment] 2023-07-19 08:06
Hi @iiSeymour I ghet the same exact problem with v0.3.2

**Comment by rainwala** [comment] 2023-07-19 08:09
The output from dorado aligner doesn'\t indicate if there is any problem, but when I use minimap2 specifically with the modified-bases bam file (as opposed to the non-modified bases bamfile) I get the following types of error:

```
minimap2 -x map-ont -t 150 /data/Homo_sapiens.GRCh38.106_no_alt_chrs.fa dorado_0-3-2_dna_r10.4.1_e8.2_400bps_hac_v4.1.0_mod_bases.bam >b
[M::mm_idx_gen::46.242*1.44] collected minimizers
[M::mm_idx_gen::60.722*5.62] sorted minimizers
[M::main::60.722*5.62] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::63.350*5.42] mid_occ = 702
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 25
[M::mm_idx_stat::65.208*5.30] distinct minimizers: 100128857 (38.82% are singletons); average occurrences: 5.521; average spacing: 5.586
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[M::worker_pipeline::65.242*5.30] mapped 5 sequences
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[M::worker_pipeline::65.269*5.30] mapped 5 sequences
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[M::worker_pipeline::65.292*5.29] mapped 4 sequences
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x map-ont -t 150 /data/Homo_sapiens.GRCh38.106_no_alt_chrs.fa dorado_0-3-2_dna_r10.4.1_e8.2_400bps_hac_v4.1.0_mod_bases.bam
[M::main] Real time: 65.402 sec; CPU: 345.827 sec; Peak RSS: 9.322 GB
```

**Comment by tijyojwad** [comment] 2023-07-19 08:41
Hi @rainwala - thanks for posting the error. Looks like we're possibly not checking for all statuses returned by mm2 correctly (but also, mm2 is reporting it as warnings and not errors...). Could you share a snippet of your file so we can reproduce this on our end?

**Comment by rainwala** [comment] 2023-07-19 10:13
Hi @tijyojwad , I tried reproducing this with a small subset (10 pod5 files) of the data, but that subset worked fine! Any tips on how to find a problematic subset of the pod5 files? Just to confirm -- you'd like me to share a bam file created by running dorado v0.3.2 basecaller with mdofied bases on a small subset of the pod5 files that reporduces this error?

**Comment by tijyojwad** [comment] 2023-07-19 10:30
Hi @rainwala - yes that's correct. I don't need the pod5 specifically. If you have a set of reads that standalone minimap2 throws a warning for, just sending those reads to be would be sufficient

**Comment by rainwala** [comment] 2023-07-19 13:17
Hi @tijyojwad , I have a bam file where that error is thrown, but it is big (~500MB). How do I share that with you? I will try to narrow it down, but otherwise, how do I share it, and is bam OK?

**Comment by rainwala** [comment] 2023-07-19 13:42
[dorado_0-3-2_pod5_small_mod_bases.bam.zip](https://github.com/nanoporetech/dorado/files/12095593/dorado_0-3-2_pod5_small_mod_bases.bam.zip)

**Comment by rainwala** [comment] 2023-07-19 13:43
so this one is actally 22MB, and I had to zip it because github doesn't accept bam files

**Comment by rainwala** [comment] 2023-07-19 13:45
if you try to align this with minimap2, it should throw the same warnings I saw.

**Comment by sklages** [comment] 2023-07-20 04:50
@rainwala - just a sidenote, you are running `minimap2` directly with BAM as query data? It should take fasta/fastq as input AFAIK ..

**Comment by rainwala** [comment] 2023-07-20 06:48
@sklages that's what I used to think before I used dorado, but minimap2 works perfectly fine with the unaligned bam output of dorado for non-modified bases. This problem is specific to the modified bases output of dorado, not an issue with minimap2's acceptance of bam files as input (which seems to work fine).

**Comment by sklages** [comment] 2023-07-20 07:26
@rainwala - interesting .. there was a feature request last year, https://github.com/lh3/minimap2/issues/977 .. but I could not find anything related in the docs ..
Just out of curiosity, which version of `minimap2` are you using?

**Comment by rainwala** [comment] 2023-07-20 07:39
@skagles, the version I am using is 2.17-r941, which makes me wonder, how is this working...(?!) as that version is from 2019! I have no idea how, but it seems to accept the bam output from dorado just fine as long as modified bases aren't used...

**Comment by sklages** [comment] 2023-07-20 08:15
@rainwala - well, strange .. anyway, I'd always go for `samtools fastq -T "*" <...> DORADO_BAM | minimap2 <...>` as long as BAM input for minimap2 is not officially supported/documented.

**Comment by Psy-Fer** [comment] 2023-07-20 08:38
Hey,

make sure your samtools is at least 1.16 as pointed out here https://github.com/nanoporetech/dorado/issues/298#issuecomment-1637649166

**Comment by rainwala** [comment] 2023-07-20 08:42
So, I re-rean with samtools 1.1.7, and I got this now:
`Failed to read header for "dorado_0-3-2_pod5_small_mod_bases.bam"`

So I think it's the same problem that is preventing minimap2 from aligning this modified-bases dorado output bam

**Comment by sklages** [comment] 2023-07-20 08:45
what is the output of `~/samtools-1.17/samtools view -H dorado_0-3-2_pod5_small_mod_bases.bam`?

**Comment by tijyojwad** [comment] 2023-07-20 10:59
@rainwala It looks like minimap2 isn't really reading the BAM file you sent me properly. It complains of things like
```
[WARNING] failed to parse the FASTA/FASTQ record next to 'nsi?!'. Continue anyway.
```
which tells me it's not parsing the records correctly.

**Comment by tijyojwad** [comment] 2023-07-20 10:59
I'm able to map the BAM file you sent using dorado aligner though

**Comment by rainwala** [comment] 2023-07-20 11:01
Yes it will map with droado aligner, but the output is really reduced comapred to what's expected. See this from the original comment:

"When I run dorado basecaller followed by dorado aligner, using the dna_r10.4.1_e8.2_400bps_hac_v4.1.0 model, I get a bam file that is 74GB in size. When I do the same with the modified-bases option, I get a bam file that is 1.9GB in size. Using the samtools veiw command to select reads from a promoter region I am interested in gives me 75 reads from the unmodifed bam file, and only 1 read from the modified bam file.

Using the modified bases option seems to lose a lot of reads after alignment compared with the unmodified bases option., What could be causing this behaviour?"

**Comment by rainwala** [comment] 2023-07-20 11:07
@sklages I had made a mistake in making the small modified bases bam file. I re-made that, and ran the ~/samtools-1.17/samtools fastq -T '*' command to generate fastq and tried mapping that with minimap2, and that seemed to work!

I'm now going to try that route for the original file (i..e not made from a subset of my data). If that works and minimap2 can align it without losing data, then that is a workaround for me, altough I'm still interested to know why dorado aligner doesn't complain but seems to loise data using modified-bases as input.

**Comment by tijyojwad** [comment] 2023-07-20 12:48
@rainwala I meant that with the file you provided me, I was able to get the same results from
```
samtools fastq -T '*' dorado_0-3-2_pod5_small_mod_bases.bam > tmp.fastq
minimap2 -x map-ont <ref.fq> tmp.fastq > mm2.bam
```

and running
```
dorado aligner <ref.fq> dorado_0-3-2_pod5_small_mod_bases.bam > dorado.bam
```

I was under the impression that I would also see fewer records aligned this way...

**Comment by rainwala** [comment] 2023-07-20 13:41
Hi @tijyojwad , I hadn't tested dorado aligner with the smaller subet that I gave you. If you got the same results from mm2 and dorado for that file, then maybe that file isn't as representative of the whole dataset as I had hoped.

I'm currently testing converting the modified-bases dorado bam output to fastq using samtools and aligning that using mm2. If that works properly I will try modkit and modbamtools on the mm2 output (which is what I wanted to use on the methylation bam in the first place).

**Comment by rainwala** [comment] 2023-07-21 07:50
@sklages @Psy-Fer , the command you gave to convert bam to fastq (`samtools fastq -T "*" <...> DORADO_BAM`  ) seemed to haev removed all of the modifed bases tags from the resulting fastq file.

when I tried using modkit pileup on the result of applying mm2 to that fastq (after converting from sam to bam), it skipped all the readss and the logs showed that all reads had "no mod tags"

Is there a version of the samtools fastq command that preserves the mod tags from dorado?

**Comment by rainwala** [comment] 2023-07-21 08:21
HI @tijyojwad , I think I would need to share a bigger file with you to reproduce the issue on your side. Is there a convenient way for me to do that? Otherwise, does dorado aligner have a log that will say if reads are getting discarded?

**Comment by sklages** [comment] 2023-07-21 08:29
> Is there a version of the samtools fastq command that preserves the mod tags from dorado?

yes, as already mentioned by @Psy-Fer  version 1.16 -- see https://github.com/nanoporetech/dorado/issues/302#issuecomment-1643514731

**Comment by sklages** [comment] 2023-07-21 09:03
@rainwala - even for the biggest bam files, there is no need to run `samtools` with 150 threads .. :-)

Have you checked your BAM that the modbases tags are actually present? Also, have you checked your fastq file headers that the modbases tags are really absent?

` -T "*"` simply transfers all tags to the fastq header .. not specifically MM/ML ..

**Comment by rainwala** [comment] 2023-07-21 09:12
@sklages thank you for the advice on threads :) How does one check that the modbase tags are present in the BAM file and check that they are absent in fastq?

**Comment by sklages** [comment] 2023-07-21 09:54
@rainwala - you can check your BAM file in the terminal with sth like `~/samtools-1.17/samtools view BAM_FILE | less` and visually inspect if the tags are present.

And for the fastqs just some `grep ^@ UNCOMPRESSED_FASTQ` .. and again, check visually for presence of the tags.

**Comment by rainwala** [comment] 2023-07-21 09:57
Here are the first couple of reads from the dorado mod bases bam, I think they show methylation as the MM tag is there:

```
1b360b03-e6a7-419c-abb8-ee907eabd16a    4       *       0       0       *       *       0       0       TATGTTATGTATAGTCTACTTGGTTCAGTTGGTGTTGCTCCCAATGTATATATTCTATACTGTACAAATTTCAAGGTGCCCAAACCATGTATTATGTCTCTACATGGAATCTGAAGTTGCATCAAATATATATTTTTATTCTGTACATAAAATATCAAAGTACACCAAATATATATTCTATAGTGTACATAAATATCAAAGTACCCAAACTATACATTATATACTGTACATAAAATATGAAATTACATCAAATATATATTATATTAGGTACAGAAAATATGAAAGTACATCAAATATAGATTATATACTGTACATAAAATACCAAAGTACCCCAAATATATATTTTATACTGTACATGAAATATCAAAGCTCACAAACTATATATTTTATCATGTACATAAAATATCAAAGTACCCAAGGTATATATTCTACACTGTACTAAAAATATCAAAGTACCCAAAGCATGTATTATATACTGTACATAAAATATGAAAGTACATCAAATATATATTTATTATTGTTACATAAAATATAGAAGTACACCCAAATATATATTCTATAGTGTACATAAAATATCAAAGTACCCAAACTATACTTTATATACTGTACATAAAATATGAAATTACAGCAAATATATATTAGTTACATAAAATATGAAAGTACATCAAATATAGATTATATACTGTACATAAAATACCAAAGTAACCCAAATATATATTTTATCTGTACATGAAATCACAATATTTGGT  ''(./2-/--)'%%%%'%%&((-/-)())(%##$&%%%&&&&&'-.--+-.14/*,,,)))%'''+')+*'&(*)*))*+*'**.,,+..*))'(&&%$%'&&*+&&&&'*''')///,,//9;>?BA@?B??BJDJGA<667788?=<=@=?21))+0321188899DEEFDFFBA><==?;;::==:8)))+,-(((0;;:8988:B@===@<=<<AB==;97673.--,//332222?BHD@<<=:5:>?@>@GA?B@BHGDD;:99:;;;?FGCAC=>>SL>><=>=DCFDDCC>>>=@AAEE8877=;==>ISLED::9:CG=;:;:=<>CFEE@BAC?IHHLD=<;;><<=::;BC9933463*(''+567678;;:::;=A>>(''''55==:<AHI<<2144><;<?=<>69559=C9;4+*)*566))*****??JEDB<==>G<;::;;==C888>@775496642/-.56<>@DGKJHE=;;HG@><7:9999=:943311:552''&&&*')01+,57955'''((0*)((++*-----++,,0.0235445778>>?GKISFD6666:989<62***>??D888IHEFFC?@>=?<=>>CFKEEE@@AFPSA>=;:::=CDC=:77?@<===??>>ELLFDE==>IF;;:<==BCCECFD===>BBCBB>>=<?=???EJHHEA?;;FH@?><<;<>BFC@??<752103'&&)....//265'%%%(()((&%&&  qs:i:14 du:f:1.6135     ns:i:6454       ts:i:10 mx:i:1  ch:i:1554       st:Z:2023-05-11T06:27:01.111+00:00      rn:i:60832      fn:Z:PAM24309_pass_fe6b6665_902b2abd_5222.pod5       sm:f:98.1837    sd:f:28.5048    sv:Z:quantile   dx:i:0  RG:Z:902b2abd979b3f2c225c9016a6f2e174fe3adf12_dna_r10.4.1_e8.2_400bps_hac@v4.1.0        MM:Z:C+h?;C+m?; ML:B:C
37b444e8-f272-48d1-a3c6-e02619bc393b    4       *       0       0       *       *       0       0       ATGTTATGTTAGTTCTTACTTGGTTCAGTTCCATTGCCTTGTATATAATAAGAATAGTCTTGTCCTTTCTTCTGGTCTGGGCTGGTATTAGGGGAGCTATTTTTGCACCTTCCTTCTACCAGAGGTGCCTCTGCTAGAGGTTCTTAGTAGAGTCCCTTCCTGCCACAACAAAAGATCCCCACTGGATTTCTCTTGAAGAAACTGTACCCCATTGACTTTTTCTTGACTTTTAAAAATGGTGTTTATGAGAACTTTTTTTGAGACTTGCAGCTTGTCTCATTTTTGCTTCTCTGAAATGCCACACTACCCCTGTGCCCATGACCACTGCCATGTAGAAAGAAAGCTGGCAATCCTTTAATCTCTTGTACATACAGATGCACTTTAGCACTCTTTACATTGCATTCTACTTCTTGGTGCACAGGACTCTCCCTAGCCACAGGGAGCTTAGGGCAGAGTTATCTTCATTTATCTTTGTATGCCCAGTCCTTGCACAGAGTATGTTCTCAGTATACCTTCACTGATTGTAAAGAACTGTAGTGGTCAATGGCTCTATAGAGCAGGTGCTGTTCCTCAGACTCTGGGAGGAACAACTGTGAGGGAAGCACAGGCTTACCTGAAGAGTAGTTGCCATGTGCTCTAGGGTGGCAATTCATG&&')-%''*'$$&'%'(%&$&'),,/*))*(&$$$####&%&''&&%%%%$##%$$##$%+,44439<6=9448777811235444376468=AB?>>>CB:9:;??:88:9>;<:<..>:;?>9988869:?@A5,-45650//..522447;;;<>6A===>;;<<<?AKKPDC@?A@>=>=9:::@><44/-.DA@?EAB>:****::<G@A?=>ISC@:<5C><=EC78;<883789554371111944496;=:-**+((((**+++,8:997667?BC>200,-'(')+,.33327;9987656695-)**+?=;99:=>>;'&&&')&'*+0;<;999669:;<<:9))))BAB@@A++**55-+'%%&(***++-'/3:;>>>A>9?EFII>>==@??<<<<@:7667554342,,3'&&(*5(((')'&&0*-.$$$$&&./3..--.('%%%'7:=BA@<<>D>>??=<<;::99:?A@BA@?;:=<;;<97467444<<;887:;?AA85021+)(((&%$%$&%%%$$+&$$%(6//..005456=?>;;;;@>?;34/873239::=>;7>;;;9;>=??>433;AAC6555::9/...:94/49887953446;<;<=@A;::9*)),+''''++&#$$#     qs:i:13 du:f:1.346      ns:i:5384       ts:i:10 mx:i:3  ch:i:717        st:Z:2023-05-11T06:26:58.284+00:00   rn:i:76929      fn:Z:PAM24309_pass_fe6b6665_902b2abd_5222.pod5  sm:f:102.557    sd:f:26.89      sv:Z:quantile   dx:i:0  RG:Z:902b2abd979b3f2c225c9016a6f2e174fe3adf12_dna_r10.4.1_e8.2_400bps_hac@v4.1.0        MM:Z:C+h?;C+m?; ML:B:C
```

and here are the first couple  of reads in the fastq:
```

@155117a0-93c2-413f-93e1-214b627413da   qs:i:11 du:f:1.15975    ns:i:4639       ts:i:10 mx:i:4  ch:i:1204       st:Z:2023-05-11T06:27:04.373+00:00      rn:i:69113      fn:Z:PAM24309_pass_fe6b6665_902b2abd_5222.pod5  sm:f:98.2884    sd:f:28.0133    sv:Z:quantile        dx:i:0  RG:Z:902b2abd979b3f2c225c9016a6f2e174fe3adf12_dna_r10.4.1_e8.2_400bps_sup@v4.1.0        MM:Z:C+h?;C+m?; ML:B:C
@937c05c9-b4fc-48d0-bf4e-a8c2c09e0a5d   qs:i:11 du:f:1.668      ns:i:6672       ts:i:10 mx:i:3  ch:i:586        st:Z:2023-05-11T06:27:05.192+00:00      rn:i:76702      fn:Z:PAM24309_pass_fe6b6665_902b2abd_5222.pod5  sm:f:98.1135    sd:f:31.1025    sv:Z:quantile        dx:i:0  RG:Z:902b2abd979b3f2c225c9016a6f2e174fe3adf12_dna_r10.4.1_e8.2_400bps_sup@v4.1.0        MM:Z:C+h?;C+m?; ML:B:C
```

It looks like both have the tags, so I'm really confused by what is going on...

**Comment by rainwala** [comment] 2023-07-21 10:00
In the minimap2 output (using the fastq as input), the rsulting bam (after converting from sam) might not have the methylation tags. Here is what I get for that output:

```
e656e1ac-c254-44b5-95f5-7aa61ac253a6    256     chr1    10001   0       1391S108M1I41M5I28M1I53M1D16M1D6M1D8M1I66M1D7M5D7M4D7M5D7M5D23M7D21M5D35M57S    *       0       0       *       *       NM:i:48 ms:i:694        AS:i:694        nn:i:0  tp:A:S  cm:i:19      s1:i:109        de:f:0.0425     rl:i:1692
32285ffd-5a51-42cc-8144-3ac839e1a158    256     chr1    10001   0       3951S108M2I69M1I5M1I18M13I5M5I42M1D37M36D31M1I37M1D31M1I7M5D6M1D176M21D51M13S   *       0       0       *       *       NM:i:111        ms:i:884        AS:i:901        nn:i:0  tp:A:S       cm:i:48 s1:i:301        de:f:0.055      rl:i:4218
```

**Comment by sklages** [comment] 2023-07-21 10:06
This is probably due to the "empty" ML tags? I had an issue with empty ML tags when merging dorado unaligned BAM including methylation info with `GATK MergeSamFiles` ...

**Comment by rainwala** [comment] 2023-07-21 10:24
I found the answer! https://github.com/lh3/minimap2/issues/964
I didn't know about the -y flag on mm2...

**Comment by Psy-Fer** [comment] 2023-07-21 11:11
So does it all work now?

And to be fair, it's not like there is some kind of centralised place to learn this kind of specific thing. 

Perhaps ONT can add another docs file that has some common workflow stuff. Specifically things like basecalling a uBAM with samtools fastq -T... | minimap2 ... -y... and the version requirements and all that jazz, as it has come up a few times now.

**Comment by rainwala** [comment] 2023-07-21 12:26
Thanks @Psy-Fer and @sklages , it does work now! modkit is working with the reads that came out of mm2 with the -y flag, instead of skipping everything. The aligned bam file from the pure dorado workflow is still a *lot* smaller than than from the mm2 workflow. To spell it out:

1) pure dorado: 
dorado basecaller --modified-bases -> dorado aligner = ~2GB bamfile with methylation tags

2) dorado plus mm2
dorado basecaller --modified-bases -> fastq -T '*' -> mm2 -y -> samtools sort = ~80GB bamfile with methylation tags

I'm hesitant to close this issue even though I have found a workaround, as it still seems like dorado aligner is getting something wrong. @tijyojwad , do you have any suggestions for how to share bigger bam files or to find specific problematic reads that let you reproduce the discrepancy?

**Comment by tijyojwad** [comment] 2023-07-21 17:54
Hi @rainwala - I agree we shouldn't close the issue yet. I can send you a link to upload the data to. Is there an email address I can use for that?

**Comment by sklages** [comment] 2023-07-21 18:16
>The aligned bam file from the pure dorado workflow is still a _lot_ smaller than than from the mm2 workflow. Specifically:
> 
> 1. pure dorado:
>    dorado basecaller --modified-bases -> dorado aligner = ~2GB bamfile with methylation tags
> 2. dorado plus mm2
>    dorado basecaller --modified-bases -> fastq -T '*' -> mm2 -y -> samtools sort = ~80GB bamfile with methylation tags

@rainwala - depending on how you have called `samtools sort` after `minimap2` alignment, you might have ended up with a large `SAM` file (which is the default output of `minimap2`) vs. a smaller `BAM` file (which is the default output of `dorado`).  

- BAM is binary format, SAM is text 
```
€ file sample.basecalls*
sample.basecalls-sup.5mCG.bam: gzip compressed data, extra field, original size 0
sample.basecalls-sup.5mCG.sam: Sequence Alignment/Map (SAM), with header version 1.6
```

**Comment by rainwala** [comment] 2023-07-21 21:21
Hi @sklages I did know that bam is binary and sam is text, and I find that with the samtools sort command I used, I get the binary format, so that's not explaining the discrepancy here. Plus there is the difference between dorado aligner when modified_bases are used vs when they aren't, which I refer right at the top of this thread:

"When I run dorado basecaller followed by dorado aligner, using the dna_r10.4.1_e8.2_400bps_hac_v4.1.0 model, I get a bam file that is 74GB in size. When I do the same with the modified-bases option, I get a bam file that is 1.9GB in size. Using the samtools veiw command to select reads from a promoter region I am interested in gives me 75 reads from the unmodifed bam file, and only 1 read from the modified bam file."

**Comment by sklages** [comment] 2023-07-22 06:17
@rainwala - next you could look at the type of records in your BAM files that may explain the huge difference (given that both dorado and minimap2 doing a good job). Unaligned reads? Secondary alignments? Supplementary alignments? `samtools view -f tag BAM` ...

**Comment by adbeggs** [comment] 2023-09-17 13:24
Hi all,

I'm having exactly the same problem... when I try and aligned modified basecalls using the inbuild alignment I get a fantastically low mapped percentage (0.64%) when using both t2t and hg38.  When run dorado with alignment without modified base calls on alignment percentage goes up to 99.9%.

If I output to SAM/uBAM first then try and align with minimap2 using samtools fastq and the -y option I get proper mapping percentages, so there may be some issue with how dorado is passing this data onto minimap2?

**Comment by adbeggs** [comment] 2023-09-17 13:39
Hmm the plots thickens. In fact it *doesn't* increase the mapping percentage when I use a uBAM. Going to try updating my version of minimap2 as it's a little old

**Comment by rainwala** [comment] 2023-09-17 13:42
Hi Andrew, yes I had to update my version of minimap2 to get it to work.

**Comment by adbeggs** [comment] 2023-09-17 14:26
Mystery solved... my fault totally (although I did need to update minimap2). Was basecalling a relatively recent project brought in by someone else who were using LSK110 kit and 9.4.1 flowcells!!!!

**Comment by weishwu** [comment] 2023-10-04 18:05
Hi @adbeggs or anyone else. Could you tell me what exactly I should do to get `dorado aligner` to work properly? I'm getting the same problem here: `dorado aligner` only processed a small percentage of the reads.

My data information:

```
Flow cell type: FLO-PRO114M
Kit type: SQK-LSK114-XL
MinKNOW: 23.07.5
Dorado basecalling model: dna_r10.4.1_e8.2_400bps_sup@v4.2.0
Dorado modified model: dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2
```

Thanks.

**Comment by tijyojwad** [comment] 2023-10-04 18:55
@adbeggs @weishwu - would any of you be able to share a dataset (or a snippet of it) where `dorado aligner` is not working as intended?

**Comment by weishwu** [comment] 2023-10-04 19:24
@tijyojwad What's the best way to share data of big size with you? I'm trying to subset it while keeping the capacity to show what's going on.

**Comment by weishwu** [comment] 2023-10-04 20:57
A little more information about my alignment:

Input uBAM flagstat:
```
9305725 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

Output aligned BAM flagstat:
```
1407133 + 0 in total (QC-passed reads + QC-failed reads)
301323 + 0 secondary
105810 + 0 supplementary
0 + 0 duplicates
1404846 + 0 mapped (99.84% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

Dorado aligner log:
```
[2023-10-04 11:22:34.932] [info] > Index parameters input by user: kmer size=15 and window size=10.
[2023-10-04 11:24:03.701] [info] > starting alignment
[2023-10-04 11:39:42.475] [info] > Reads basecalled: 1000000
[2023-10-04 11:39:42.475] [info] > finished alignment
[2023-10-04 11:39:42.475] [info] > total/primary/unmapped 1407133/997713/2287
```
That __Reads basecalled: 1000000__ is suspicious. Looks like some sort of subsetting or capping was going on.
I'm still working on generating a small dataset for troubleshooting.

**Comment by weishwu** [comment] 2023-10-04 21:44
When I subset 1.9 million reads from the uBAM and rerun dorado aligner, I got the same 1000000 cap again:
```
[2023-10-04 17:11:10.589] [info] > Index parameters input by user: kmer size=15 and window size=10.
[2023-10-04 17:12:36.256] [info] > starting alignment
[2023-10-04 17:28:05.921] [info] > Reads basecalled: 1000000
[2023-10-04 17:28:05.921] [info] > finished alignment
[2023-10-04 17:28:05.921] [info] > total/primary/unmapped 1407546/997650/2350
```

Flagstat of uBAM:
```
1860979 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

Flagstat of aligned BAM:
```
1407546 + 0 in total (QC-passed reads + QC-failed reads)
301677 + 0 secondary
105869 + 0 supplementary
0 + 0 duplicates
1405196 + 0 mapped (99.83% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

@tijyojwad I can share with you this uBAM file that contains 1.9 million reads. Could I use Globus to transfer it? If so, could you tell me your Globus account name? Thanks.

**Comment by tijyojwad** [comment] 2023-10-04 22:33
Hi @weishwu - what version of dorado are you using? We had a bug where we were limiting the number of alignments. We've fixed it internally and will be released soon. You can work around it by setting `--max-reads 10000000` which shoul be above your threshold.

For data transfer, can you share your email with me? I can send a secure upload link

**Comment by weishwu** [comment] 2023-10-04 23:54
@tijyojwad I used v0.3.2. I see that you lifted the `max-reads` limit in v0.3.4. Sorry that I overlooked the `max-reads` parameter, or somehow miscount the numbers in the default value. I was blind!
I'll rerun it with `--max-reads 10000000` and I'm sure this should produce the correct output. I'll let you know if I need your help. Thanks!

**Comment by tijyojwad** [comment] 2023-10-05 21:04
Thanks @weishwu - yeah if you could confirm that you get correct outputs from `dorado aligner` that match mm2 outputs that'd be great!

**Comment by hamid89** [comment] 2024-01-23 17:26
hello guyz,
I have a question related to modbam2bed. I followed the same step as mentioned here to map the uSAM using minimap as following.
samtools fastq -T MM,ML {input.sam_file} | minimap2 -a -x map-ont -Y -secondary==no -t {threads} {input.reference_index} - > {output.mapped_sam}
Should I see the MM and ML tags in mapped SAM? 
secondly, I successfully generated the bedgraph using modbam2bed but which I column from the bedgraph I should consider for scoring the modified base.

please let me know if you need more information. I have no idea how minimap is keeping track of the modified bases which are mapped from fastq to reference.

**Comment by tijyojwad** [comment] 2024-01-23 21:00
Closing this issue since it's been open for a while and we haven't been able to reproduce this on our end.

**Closed by tijyojwad** 2024-01-23 21:00 UTC
