### ISSUE TITLE
Problem downloading models

### ISSUE THREAD

**Issue by rmorenoayala** [nanoporetech/dorado#74] opened 2023-01-05 15:03 UTC
When I try to download all models or individual ones, I get: [error] Failed to download.

**Comment by rmorenoayala** [comment] 2023-01-06 15:01
e.g. Quadro P1000

**Comment by vellamike** [comment] 2023-01-06 15:01
Dorado only works on Volta and newer devices. Pascal generation is not expected to work.

Can you give some more detail on your model download issue? This seems like it could perhaps be a a firewall problem?

**Comment by rmorenoayala** [comment] 2023-01-06 15:26
Hi, thank you for answering. When I try to download specific models with 'dorado download --model' or all 'dorado download --model all', I get the same error message:

[2023-01-06 16:19:31.457] [info]  - downloading dna_r10.4.1_e8.2_260bps_fast@v3.5.2
[2023-01-06 16:19:33.599] [error] Failed to download dna_r10.4.1_e8.2_260bps_fast@v3.5.2
...

Too bad that it doesn't support my GPU card. I will try with guppy. Thank you.

**Comment by vellamike** [comment] 2023-01-06 15:36
Could you try, in the same directory where dorado is failing to download the model, to execute the following command:

```
wget --no-check-certificate  https://nanoporetech.box.com/shared/static/uegadbtxw3j76ommk092a9711tk6unli.zip
```

**Comment by rmorenoayala** [comment] 2023-01-06 15:41
Ok, I get the following:

--2023-01-06 16:38:31--  https://nanoporetech.box.com/shared/static/uegadbtxw3j76ommk092a9711tk6unli.zip
Resolving nanoporetech.box.com (nanoporetech.box.com)... 74.112.186.144
Connecting to nanoporetech.box.com (nanoporetech.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/uegadbtxw3j76ommk092a9711tk6unli.zip [following]
--2023-01-06 16:38:31--  https://nanoporetech.box.com/public/static/uegadbtxw3j76ommk092a9711tk6unli.zip
Reusing existing connection to nanoporetech.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nanoporetech.ent.box.com/public/static/uegadbtxw3j76ommk092a9711tk6unli.zip [following]
--2023-01-06 16:38:32--  https://nanoporetech.ent.box.com/public/static/uegadbtxw3j76ommk092a9711tk6unli.zip
Resolving nanoporetech.ent.box.com (nanoporetech.ent.box.com)... 74.112.186.144
Connecting to nanoporetech.ent.box.com (nanoporetech.ent.box.com)|74.112.186.144|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ec2euc1.boxcloud.com/d/1/a1!pCPN7lT2tzpWSiM2u41FYcJhop7mrirsD-rwY467v6uOwqJwX-t0OlsricYL7e3DaHqaFvi5lV_wnJVeBPogeSGp6j0u_RZQxOm2qUbRO2-Z6W00gOMwXdcIF6KOpsDdMqFgvJdnI98LF6LvOm16baZmFRZLdl-tRIWfjLICQMw9vom0IQdinHMO1csdp7kvqZZhnbvfRkXSoP6A_YFVz642txSwe0jTDLRj7H9_PS6SpXVc22zKiHg0ZS79pNMu6z9fSQbHvXp073DClEc-_gpLjlgnrZQmvGO3C9SA42DUb-jOrrRrRXeu46YghUCoF2FM27rX-iDrlU42dPufFDH5xKkxxzAiNcW85o4G7gBIOEDTNx3BVvzaWvYEj1W7C-b1bxitT9gPBMe9OZTqvslrb2TeyTqYeKKnNog9xn2M0XJlTHy-UcJN1qdMCKU8mC8HKTBG-l8FzLEZzMXoI4Y59ojUxWOea2BttmEvjNrm7eg80TWabic-0KBNIsJYvtBX_F_xT8Au2qWibjbwgXzE18SQxUp8GRp7PKDap-xLW9Am0lWTwuIJQnf56aBsxks_aMX-l7400uM4A18jdbShWkyMUPU9g4PHddje9RBJLlwrcCNENyTBonA6erQnfAapCiMoMNDr255sajRQOZjJi229zx2p40FteKFZJPG1u9eelsEFWJMoVoa3Pl_EhgZLyb9YPfCLJSLfXg7ekduzb2rRQ43PLItot8PsJCdqVuZwmKEuQkysTQmNMjhIvPMwfKve7LQfOfIXSKQbs4D8Xgx4q25G2lkPspWa3_qVXxmSGnMClSzBxhk7ZlmpIUNUlbsWKfftKAGRO7RCdySmiESfyPtcgb-Rj53vDc7QaQ8S9Mrs77qrDxqlhEOtDgwmWFcJKPn_7N0_35zdw6Y6Tnc95AEfjA_XRVVSlHOLnxU2pSTejMLRiWiAe5a0WAnzS1O8JeAMZOnWufvVNyDKjxhKfBgHIqVOYHfjMO24SwxjnwBFdklcu6FfudyDapXrhe0d2q3p6ZfP6eOFmLD9TBzPr5OpM_CvlI6ai9CqAGUO6RbJqTzWGqld--Pr9foOZfpTH7ZVmdUZSis6ahwLu5f4jZbQnO0JrKD-zK3DAnyRD4wh3C6I7ehxee214M6HhUuJffVNGXnYUltyPCICtM6DvB3N0x5tbAU4k22rOY1EDKhXSTPACdNBBLu2xmEHaW8pizeo_-1x5zvXruFyXIgIDkk37dpmq7hmoXA6WjkICEX0fqjWPR_Wyfp-PPH-vLnpHrmQDYjGimvLOk3hm0SkCekTnKSAmtXeJTpeF0p8xRJ-ICesswPzDNxdvwJz9tTaNna3okNL0hNRPbo9ofwEcx3vUqguhfF2o-eLQP87h0AQ1B1B9-5FmQGowG41wXGEYo6pW8ZGDRZnvLkEMUNxkQMe_7nZDIPMiERoB6cAmA../download [following]
--2023-01-06 16:38:32--  https://ec2euc1.boxcloud.com/d/1/a1!pCPN7lT2tzpWSiM2u41FYcJhop7mrirsD-rwY467v6uOwqJwX-t0OlsricYL7e3DaHqaFvi5lV_wnJVeBPogeSGp6j0u_RZQxOm2qUbRO2-Z6W00gOMwXdcIF6KOpsDdMqFgvJdnI98LF6LvOm16baZmFRZLdl-tRIWfjLICQMw9vom0IQdinHMO1csdp7kvqZZhnbvfRkXSoP6A_YFVz642txSwe0jTDLRj7H9_PS6SpXVc22zKiHg0ZS79pNMu6z9fSQbHvXp073DClEc-_gpLjlgnrZQmvGO3C9SA42DUb-jOrrRrRXeu46YghUCoF2FM27rX-iDrlU42dPufFDH5xKkxxzAiNcW85o4G7gBIOEDTNx3BVvzaWvYEj1W7C-b1bxitT9gPBMe9OZTqvslrb2TeyTqYeKKnNog9xn2M0XJlTHy-UcJN1qdMCKU8mC8HKTBG-l8FzLEZzMXoI4Y59ojUxWOea2BttmEvjNrm7eg80TWabic-0KBNIsJYvtBX_F_xT8Au2qWibjbwgXzE18SQxUp8GRp7PKDap-xLW9Am0lWTwuIJQnf56aBsxks_aMX-l7400uM4A18jdbShWkyMUPU9g4PHddje9RBJLlwrcCNENyTBonA6erQnfAapCiMoMNDr255sajRQOZjJi229zx2p40FteKFZJPG1u9eelsEFWJMoVoa3Pl_EhgZLyb9YPfCLJSLfXg7ekduzb2rRQ43PLItot8PsJCdqVuZwmKEuQkysTQmNMjhIvPMwfKve7LQfOfIXSKQbs4D8Xgx4q25G2lkPspWa3_qVXxmSGnMClSzBxhk7ZlmpIUNUlbsWKfftKAGRO7RCdySmiESfyPtcgb-Rj53vDc7QaQ8S9Mrs77qrDxqlhEOtDgwmWFcJKPn_7N0_35zdw6Y6Tnc95AEfjA_XRVVSlHOLnxU2pSTejMLRiWiAe5a0WAnzS1O8JeAMZOnWufvVNyDKjxhKfBgHIqVOYHfjMO24SwxjnwBFdklcu6FfudyDapXrhe0d2q3p6ZfP6eOFmLD9TBzPr5OpM_CvlI6ai9CqAGUO6RbJqTzWGqld--Pr9foOZfpTH7ZVmdUZSis6ahwLu5f4jZbQnO0JrKD-zK3DAnyRD4wh3C6I7ehxee214M6HhUuJffVNGXnYUltyPCICtM6DvB3N0x5tbAU4k22rOY1EDKhXSTPACdNBBLu2xmEHaW8pizeo_-1x5zvXruFyXIgIDkk37dpmq7hmoXA6WjkICEX0fqjWPR_Wyfp-PPH-vLnpHrmQDYjGimvLOk3hm0SkCekTnKSAmtXeJTpeF0p8xRJ-ICesswPzDNxdvwJz9tTaNna3okNL0hNRPbo9ofwEcx3vUqguhfF2o-eLQP87h0AQ1B1B9-5FmQGowG41wXGEYo6pW8ZGDRZnvLkEMUNxkQMe_7nZDIPMiERoB6cAmA../download
Resolving ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)... 0.0.0.0, ::
Connecting to ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)|::|:443... failed: Connection refused.

**Comment by vellamike** [comment] 2023-01-06 15:43
OK - the issue seems to be at your network/OS level, could you also try:

```
wget  https://nanoporetech.box.com/shared/static/uegadbtxw3j76ommk092a9711tk6unli.zip
```

**Comment by rmorenoayala** [comment] 2023-01-06 15:44
Yes, similar response.

**Comment by vellamike** [comment] 2023-01-06 15:51
I'm afraid the problem is on your end, DNS is not resolving correctly:

```
Resolving ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)... 0.0.0.0, ::
Connecting to ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to ec2euc1.boxcloud.com (ec2euc1.boxcloud.com)|::|:443... failed: Connection refused ```
```

It's not a Dorado issue as such - It seems like you just can't download from our hosting provider, this could be a firewall, misconfigured network settings on your OS etc. You probably need to speak your IT department?

**Comment by incoherentian** [comment] 2023-01-12 12:10
> It's not a Dorado issue as such - It seems like you just can't download from our hosting provider, this could be a firewall, misconfigured network settings on your OS etc. You probably need to speak your IT department?

Will dorado models ever be _easily_ downloadable without using the dorado CLI? 

I've had to log in to a separate node to download models, as our GPU compute nodes are similarly firewalled for good reason. If I could have simply found a clearly defined model repository to download using other means (e.g. listing dna_r10.4.1_e8.2_260bps_fast@v3.5.2 for https://nanoporetech.box.com/shared/static/uegadbtxw3j76ommk092a9711tk6unli.zip ), that would have been great!

**Comment by rmorenoayala** [comment] 2023-01-12 15:15
I agree, it would be very useful.

**Comment by mkleinecke** [comment] 2023-01-19 07:10
Hi - I also can not download anything using the dorado download command. The wget works but how do I know which is which model? I would need the dna_r9.4.1_e8_sup@v3.3 and dna_r10.4.1_e8.2_260bps_sup@v4.0.0

Thanks :)

**Comment by tnn111** [comment] 2023-01-20 07:14
I can't download models through dorado either and I don't think it's a firewall issue on my end since I have no difficulty with the wget ones you posted.

**Comment by madhav-madhusoodanan** [comment] 2023-02-04 21:08
Don't worry

All you have to do is to follow the models in this [page](https://github.com/nanoporetech/dorado/blob/master/dorado/utils/models.h).

You will see the `shared/static/<FILE>.zip` zip file path corresponding to each model.

Go to Google Colaboratory and run the following into a code cell (with the path of the zip file according to the model of choice)

```
!wget --no-check-certificate  https://nanoporetech.box.com/shared/static/<FILE>.zip
```

For those who are impatient and wouldn't mind a quick and dirty way of downloading the models :)

**Comment by incoherentian** [comment] 2023-02-04 21:52
> a quick and dirty way of downloading the models :)

Works! Thanks for that Madhav!

**Comment by iiSeymour** [comment] 2023-02-19 12:00
The model URLs are all direct now so you don't need to look up the hash - i.e to download `dna_r10.4.1_e8.2_400bps_hac@v4.1.0`

```
$ wget https://cdn.oxfordnanoportal.com/software/analysis/dorado/dna_r10.4.1_e8.2_400bps_hac@v4.1.0.zip
```

**Closed** 2023-12-04 18:31 UTC

**Comment by OndroV** [comment] 2025-05-15 05:27
Hi, I'm not able to basecall with dorado at work and it seems to be linked to this issue. Would you please give me an advice? When I'm connected to cellular data network, it runs fine, but each run consumes quite a lot of data. Anyways, I need to run it regularly through the institutional ethernet, which fails to download the models:

> C:\Users\PC\Documents\DNA_software\dorado-0.9.5-win64\bin\dorado basecaller sup pod5_skip\ --emit-fastq --models-directory C:\Users\PC\Documents\DNA_software\dorado-0.9.5-win64\models\ | out-file -encoding Ascii fastq\out_ethernet20250515.fastq
[2025-05-15 07:16:41.513] [info] Running: "basecaller" "sup" "pod5_skip\" "--emit-fastq" "--models-directory" "C:\Users\PC\Documents\DNA_software\dorado-0.9.5-win64\models\"
[2025-05-15 07:16:41.522] [info]  - Note: FASTQ output is not recommended as not all data can be preserved.
[2025-05-15 07:16:41.525] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with httplib
[2025-05-15 07:17:01.596] [error] Failed to download dna_r10.4.1_e8.2_400bps_sup@v5.0.0: Connection timed out
[2025-05-15 07:17:01.598] [info]  - downloading dna_r10.4.1_e8.2_400bps_sup@v5.0.0 with curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0
curl: (28) Failed to connect to cdn.oxfordnanoportal.com port 443 after 84187 ms: Could not connect to server
[2025-05-15 07:18:25.837] [error] Failed to download dna_r10.4.1_e8.2_400bps_sup@v5.0.0: ret=28, errno=0
[2025-05-15 07:18:25.837] [error] Failed to download + simplex model: 'dna_r10.4.1_e8.2_400bps_sup@v5.0.0'.
[2025-05-15 07:18:25.837] [error] finalise() not called on a HtsFile.

The ONT support initially said that I don't need to enable any specific IP addresses for dorado, but later said that dorado requires internet connection and firewall might need to be adjusted. Our IT department has already whitelisted the IP addresses for Telemetry feedback, Software updates and EPI2ME, but basecalling still doesn't work. When I run the [suggested wget command](https://github.com/nanoporetech/dorado/issues/74#issuecomment-1435969149) in my models directory, it doesn't throw any errors, but the directory remains empty despite downloading 15015280 bytes (186984597 when trying for dna_r10.4.1_e8.2_400bps_sup@v5.0.0):
 
> PS C:\Users\PC\Documents\DNA_software\dorado-0.9.5-win64\models> wget https://cdn.oxfordnanoportal.com/software/analysis/dorado/dna_r10.4.1_e8.2_400bps_sup@v5.0.0.zip


StatusCode        : 200
StatusDescription : OK
Content           : {80, 75, 3, 4...}
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    x-amz-server-side-encryption: AES256
                    X-Cache: Miss from cloudfront
                    X-Amz-Cf-Pop: VIE50-P1
                    X-Amz-Cf-Id: JbExcLsvo4aMLTqISdQhFtAo0XGUbt-4m3SLU7cJ5csd2tmVv0lop...
Headers           : {[Connection, keep-alive], [x-amz-server-side-encryption, AES256], [X-Cache, Miss from cloudf
                    ront], [X-Amz-Cf-Pop, VIE50-P1]...}
RawContentLength  : 186984597

**Comment by OndroV** [comment] 2025-05-16 06:37
OK, I can eventually basecall on ethernet if I download the model manually via browser, unzip and refer to the models folder with --models-directory argument. Still, it's strange and inconvenient that the model downloads don't work automatically, nor through wget.
