### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'   what():  Failed to write SAM record, error code -1

### ISSUE THREAD

**Issue by AzlanNI** [nanoporetech/dorado#579] opened 2024-01-15 13:13 UTC
Hello everyone! 

I am currently using Dorado to basecall some bacterial Data with mod call 5mc and 6mA. I encountered an Error with the following code : 

dorado basecaller --modified-bases-models /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2,/software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Myco_R10/fast5s/819_pod5/Output_pods --reference /gpfs/project/projects/DiltheyLab/projects/HematoDETECT/MethylationCfDNA/Myco_R10/Ref/819-W_R10PC.fasta > 819_non_Aligned.bam

And i got the Error: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to write SAM record, error code -1 

Does someone have an idea what went wrong ? Do u maybe have to install Minimap2 on the same Session ? 

Thanks for ur answers! 

Kind regards,
Azlan

**Comment by AzlanNI** [comment] 2024-01-15 14:40
I uploaded some pod5 files here https://1drv.ms/f/s!Av3UULkM3tzkgWeJxiWeAtC8Wrkv?e=Kcz2g9 So if anyone wants to check

**Comment by malton-ont** [comment] 2024-01-16 09:55
There's no need to install minimap2 - dorado is already linked against those libraries. Is there more info in the log messages? I'd expect to see an error message from `htslib` in there; something like `[E::bam_write1] <error message>`

Does this only occur when you use alignment? Are you able to supply the reference file?

**Comment by AzlanNI** [comment] 2024-01-16 10:55
@malton-ont sure this is the reference file  i used https://1drv.ms/f/s!Av3UULkM3tzkgXcRXRSbDqS54ClE?e=VLAjqE

i hope u can access the onedrive LInk tell me if i should upload it somewhere else. 
I also started the Job again without --reference i will edit if it runs into an Error

**Comment by malton-ont** [comment] 2024-01-16 11:59
I'm not able to reproduce the issue with the dataset and reference above, so the error message in the output is our next best lead. Is anything showing up?

**Comment by AzlanNI** [comment] 2024-01-16 12:23
Without the --reference tag i dont get any error message. Let me try it again with --reference

**Comment by AzlanNI** [comment] 2024-01-18 17:12
Okey here i am again i got it running but i am encountering a Problem. I give the Tool a reference as i posted earlier and use it as --reference but it creates not aligned.bam output so is something wrong with my input command ? @malton-ont 

thanks!

**Comment by malton-ont** [comment] 2024-01-18 17:35
Could you share how you got it running (for any future users who encounter this issue)?

Your command should be of the format:
```
dorado basecaller --modified-bases-models [model1,model2] [data_dir] --reference [reference.fasta] > output.bam
```
Note the space before the final `>` though, that seems to be missing above.

And the data and reference you attached above certainly seem to align:
```
026917f7-214a-4a98-b798-ab64e0a2f12e    16      819-W_R10PC     297858  60      50S24M1I112M3D116M1I7M1I52M39S  *       0       0
00171472-a07f-49c1-b323-bd06382168e0    0       819-W_R10PC     560146  60      39S74M1D163M52S *       0       0       
011730fe-797c-4d59-8bdf-b6a6709387ab    16      819-W_R10PC     480029  60      54S659M39S      *       0       0       
002b28de-f6b9-40a4-bbca-3ef478b2a086    16      819-W_R10PC     637211  60      107S84M1I226M37S        *       0       0
002b28de-f6b9-40a4-bbca-3ef478b2a086    2048    819-W_R10PC     637424  51      342H58M1D38M17H *       0       0
```
You can add `-v` or even `-vv` to your flags to generate more verbose output that may tell you what is happening, but without seeing that I can only guess.

**Comment by AzlanNI** [comment] 2024-01-22 15:27
Yeah sure i can post my command! But i am currently running into a problem after it worked for some sessions. It now gives out the following Error: 

Caught Torch error 'CUDA out of memory 4 times. I guess for each of the 4 GPUs i use. The Exact Error is the following 

Caught Torch error 'CUDA out of memory. Tried to allocate 4.07 GiB (GPU 3; 10.92 GiB total capacity; 5.15 GiB already allocated; 4.00 GiB free; 5.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF', clearing CUDA cache and retrying.
[2024-01-22 15:36:22.097] [warning] Caught Torch error 'CUDA out of memory. Tried to allocate 4.07 GiB (GPU 0; 10.92 GiB total capacity; 5.13 GiB already allocated; 3.66 GiB free; 5.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF', clearing CUDA cache and retrying.
[2024-01-22 16:11:11.016] [warning] Caught Torch error 'CUDA out of memory. Tried to allocate 4.07 GiB (GPU 0; 10.92 GiB total capacity; 4.71 GiB already allocated; 3.78 GiB free; 5.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF', clearing CUDA cache and retrying.
terminate called after throwing an instance of 'c10::OutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 4.07 GiB (GPU 0; 10.92 GiB total capacity; 4.77 GiB already allocated; 2.69 GiB free; 5.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /pytorch/pyold/c10/cuda/CUDACachingAllocator.cpp:913 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x2b79cd1579b7 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #1: <unknown function> + 0xa9f8645 (0x2b79cd117645 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #2: <unknown function> + 0xa9f893e (0x2b79cd11793e in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #3: <unknown function> + 0xa9f8cce (0x2b79cd117cce in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #4: <unknown function> + 0x4530bc1 (0x2b79c6c4fbc1 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #5: at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) + 0x14 (0x2b79c6c49604 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #6: at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) + 0x111 (0x2b79cb0a1f01 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #7: at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0x31 (0x2b79cb0a21d1 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #8: at::detail::empty_cuda(c10::ArrayRef<long>, c10::TensorOptions const&) + 0x10f (0x2b79cb0a233f in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #9: <unknown function> + 0xa60889b (0x2b79ccd2789b in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #10: <unknown function> + 0xa6e6386 (0x2b79cce05386 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #11: at::meta::structured_mm::meta(at::Tensor const&, at::Tensor const&) + 0x124 (0x2b79c7103104 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #12: <unknown function> + 0xa61212a (0x2b79ccd3112a in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #13: <unknown function> + 0xa6121c0 (0x2b79ccd311c0 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #14: at::_ops::mm::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x2b79c7c369c1 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #15: <unknown function> + 0x49f3b91 (0x2b79c7112b91 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #16: at::native::matmul(at::Tensor const&, at::Tensor const&) + 0x49 (0x2b79c7112fa9 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #17: <unknown function> + 0x5a58f30 (0x2b79c8177f30 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #18: at::_ops::matmul::call(at::Tensor const&, at::Tensor const&) + 0x161 (0x2b79c7d3b301 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #19: dorado() [0xa21fc8]
frame #20: dorado() [0xa227cf]
frame #21: dorado() [0x9bd815]
frame #22: dorado() [0x9bf202]
frame #23: dorado() [0x9c3521]
frame #24: dorado() [0x9a0a59]
frame #25: dorado() [0x9a0b88]
frame #26: dorado() [0x9a0de0]
frame #27: dorado() [0x9a510b]
frame #28: <unknown function> + 0x1196e380 (0x2b79d408d380 in /software/dorado/0.5.1/bin/../lib/libdorado_torch_lib.so)
frame #29: <unknown function> + 0x7ea5 (0x2b7a2f424ea5 in /lib64/libpthread.so.0)
frame #30: clone + 0x6d (0x2b7a30613b0d in /lib64/libc.so.6)

/var/spool/pbs/mom_priv/jobs/9292922.hpc-batch.SC: line 14: 10512 Aborted   

So i am now trying to understand if it is a problem with the HPC system or if my command is resulting in an Error now. This is the Command i am using 

dorado basecaller --modified-bases-models /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2,/software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 /gpfs/project/azlan/Myco_R10/819_pod5/Output_pods --reference /gpfs/project/projects/DiltheyLab/MethylationCfDNA/MycoR10/Myco_R10/Ref/819-W_R10PC.fasta > 819_Aligned_2.bam

It matches ur format in the command before @malton-ont

**Comment by malton-ont** [comment] 2024-01-22 15:38
The `'CUDA out of memory` is a known issue that occurs intermittently with certain model/GPU configurations. This will hopefully be resolved in an upcoming release. In the mean time, you can try setting the environment variable `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25` and that may resolve it.

**Comment by AzlanNI** [comment] 2024-01-22 15:43
Do i just put PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25 into the command prompt before i execute the dorado basecaller ?

**Comment by malton-ont** [comment] 2024-01-22 15:46
It needs setting as an environment variable, so you can either add it directly in front of the call to dorado:
```
PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25 dorado basecaller ...
```
or export it earlier in the script:
```
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25
dorado basecaller ...
```

**Comment by AzlanNI** [comment] 2024-01-22 15:49
Alright i will try the following and give feedback thanks for ur help! 

PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:25 dorado basecaller --modified-bases-models /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2,/software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v3 /software/dorado/0.5.1/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0 /gpfs/project/azlan/Myco_R10/819_pod5/Output_pods --reference /gpfs/project/projects/DiltheyLab/MethylationCfDNA/MycoR10/Myco_R10/Ref/819-W_R10PC.fasta> 819_Aligned_2.bam

**Comment by AzlanNI** [comment] 2024-01-24 15:22
Hey @malton-ont it all worked out and i got a Output without Errors! Thanks for ur help! May i ask u something i was looking for the threshholds dorado uses for modbases and canonbases but did not find it. Do u know what the default ones are and how i could set them if ever needed ? 

Kind regards,
Azlan

**Closed** 2024-01-24 15:27 UTC
